name: Keep EcoBin API Alive

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  ping-ecobin:
    runs-on: ubuntu-latest

    steps:
      - name: Ping EcoBin API
        run: |
          echo "Pinging EcoBin API to keep it alive..."

          API_URL="https://ecobin-sih-app.onrender.com/api/bin/submit"

          # Perform the health check
          response=$(curl -s -o /dev/null -w "%{http_code}" "$API_URL" || echo "000")

          if [ "$response" = "200" ]; then
            echo "✅ EcoBin API is alive - HTTP $response"
          else
            echo "❌ EcoBin API might be down - HTTP $response"
          fi

          echo "Ping completed at $(date)"

      - name: Log Activity
        run: |
          echo "EcoBin keep-alive job executed successfully"
          echo "Next execution in 5 minutes"
